//! The emitter state: a growing LLVM module (external declarations, string
//! globals, finished functions) plus the in-progress function (SSA counter,
//! current basic block, lexical scopes). Low-level helpers here only *emit*
//! text; the AST-walking lives in `lower.rs`.

use crate::llty::{LType, Value};
use std::collections::{BTreeSet, HashMap};

/// Accumulates a whole module while lowering one function at a time.
pub struct Codegen {
    /// `declare` lines, de-duplicated and stably ordered.
    externs: BTreeSet<String>,
    /// Global constant definitions (string literals).
    globals: Vec<String>,
    /// Rendered `define` blocks.
    funcs: Vec<String>,
    glob_count: usize,

    // ---- current function state ----
    reg_count: usize,
    label_count: usize,
    cur_lines: Vec<String>,
    cur_block: String,
    scopes: Vec<HashMap<String, Value>>,

    /// Declared parameter names per function, for named-argument ordering.
    pub(crate) fn_params: HashMap<String, Vec<String>>,
}

impl Codegen {
    pub fn new() -> Codegen {
        Codegen {
            externs: BTreeSet::new(),
            globals: Vec::new(),
            funcs: Vec::new(),
            glob_count: 0,
            reg_count: 0,
            label_count: 0,
            cur_lines: Vec::new(),
            cur_block: String::from("entry"),
            scopes: Vec::new(),
            fn_params: HashMap::new(),
        }
    }

    // ---- SSA + block naming (function-local) ----

    pub(crate) fn fresh_reg(&mut self) -> String {
        let r = format!("%r{}", self.reg_count);
        self.reg_count += 1;
        r
    }

    pub(crate) fn fresh_label(&mut self) -> String {
        let l = format!("L{}", self.label_count);
        self.label_count += 1;
        l
    }

    pub(crate) fn cur_block(&self) -> &str {
        &self.cur_block
    }

    // ---- emission ----

    pub(crate) fn emit(&mut self, line: impl Into<String>) {
        self.cur_lines.push(format!("  {}", line.into()));
    }

    /// Start a new basic block and make it current (its label becomes the
    /// predecessor recorded for any `phi` that follows).
    pub(crate) fn start_block(&mut self, label: &str) {
        self.cur_lines.push(format!("{label}:"));
        self.cur_block = label.to_string();
    }

    pub(crate) fn add_extern(&mut self, decl: impl Into<String>) {
        self.externs.insert(decl.into());
    }

    /// Intern a string literal as a private global and return an `i8*` pointing
    /// at its first byte.
    pub(crate) fn string_constant(&mut self, text: &str) -> Value {
        let (escaped, len) = escape_c_string(text);
        let name = format!("@.str.{}", self.glob_count);
        self.glob_count += 1;
        self.globals.push(format!(
            "{name} = private unnamed_addr constant [{len} x i8] c\"{escaped}\""
        ));
        let reg = self.fresh_reg();
        self.emit(format!(
            "{reg} = getelementptr [{len} x i8], [{len} x i8]* {name}, i64 0, i64 0"
        ));
        Value::new(reg, LType::Str)
    }

    // ---- scopes ----

    pub(crate) fn push_scope(&mut self) {
        self.scopes.push(HashMap::new());
    }

    pub(crate) fn pop_scope(&mut self) {
        self.scopes.pop();
    }

    pub(crate) fn bind(&mut self, name: impl Into<String>, value: Value) {
        if let Some(scope) = self.scopes.last_mut() {
            scope.insert(name.into(), value);
        }
    }

    pub(crate) fn lookup(&self, name: &str) -> Option<Value> {
        self.scopes.iter().rev().find_map(|s| s.get(name).cloned())
    }

    // ---- function framing ----

    /// Reset per-function state and open a fresh `entry` block + scope.
    pub(crate) fn begin_function(&mut self) {
        self.reg_count = 0;
        self.label_count = 0;
        self.cur_lines.clear();
        self.cur_block = String::from("entry");
        self.push_scope();
        self.cur_lines.push("entry:".to_string());
    }

    /// Render the in-progress function and append it to the module.
    pub(crate) fn finish_function(&mut self, ret: LType, name: &str, params: &[(LType, String)]) {
        let param_list = params
            .iter()
            .map(|(ty, n)| format!("{ty} %{n}"))
            .collect::<Vec<_>>()
            .join(", ");
        let body = std::mem::take(&mut self.cur_lines).join("\n");
        self.funcs
            .push(format!("define {ret} @{name}({param_list}) {{\n{body}\n}}"));
        self.pop_scope();
    }

    /// Assemble the final module text: header, externals, globals, functions.
    pub(crate) fn render(&self) -> String {
        let mut out = String::from("; Generated by osprey-rs (Rust LLVM-text backend)\n\n");
        for decl in &self.externs {
            out.push_str(decl);
            out.push('\n');
        }
        out.push('\n');
        for g in &self.globals {
            out.push_str(g);
            out.push('\n');
        }
        out.push('\n');
        out.push_str(&self.funcs.join("\n\n"));
        out.push('\n');
        out
    }
}

impl Default for Codegen {
    fn default() -> Self {
        Codegen::new()
    }
}

/// Escape a Rust string into an LLVM `c"..."` body, returning the escaped text
/// and the byte length **including** the trailing NUL. Bytes outside printable
/// ASCII (and `"`/`\`) are emitted as `\HH`.
fn escape_c_string(text: &str) -> (String, usize) {
    let mut out = String::new();
    let bytes = text.as_bytes();
    for &b in bytes {
        match b {
            b'\\' => out.push_str("\\5C"),
            b'"' => out.push_str("\\22"),
            0x20..=0x7e => out.push(b as char),
            _ => out.push_str(&format!("\\{b:02X}")),
        }
    }
    out.push_str("\\00");
    (out, bytes.len() + 1)
}
