version: "2"

severity:
  default: error

linters:
  settings:
    cyclop:
      max-complexity: 20
  default: all
  disable:
    # Consider these rules for the future
    - depguard # Allow LLVM imports
    - exhaustruct # Don't require all struct fields to be specified
    - varnamelen # Allow short variable names like 'i', 'e', etc.
    # - funcorder    # Don't enforce function ordering
    - gocritic # Disable overly pedantic suggestions
    - wsl # Don't enforce whitespace rules
    - whitespace # Don't enforce unnecessary leading newlines
    - nestif # Don't limit nested if statements
    - prealloc # Don't require slice preallocation
    - gochecknoinits # Allow init functions
    - copyloopvar # Don't require loop variable copying (Go 1.22+ feature)
    - dupl # Allow code duplication
    - forbidigo # Allow fmt.Printf and similar functions
    - forcetypeassert # Allow unchecked type assertions
    - godox # Allow TODO/FIXME comments
    - ireturn # Allow returning interfaces
    - nilerr # Allow returning nil error with non-nil value
    - nilnil # Allow returning nil, nil
    - paralleltest # Don't require t.Parallel() in tests
    - testpackage # Allow same package name for tests
    - usetesting # Don't require t.TempDir()
    - wrapcheck # Don't require wrapping external errors
    - thelper # Don't require t.Helper() calls
    - funlen # Disable function length checks (test functions need comprehensive cases)
    - gosec # Disable security checks (test files need file operations and exec calls)
    - dupword # Disable duplicate word detection (test output strings may have repeated words)

    # Ignore these rules
    - nlreturn # This rule is not beneficial for this codebase
    - godot # Comment period enforcement disabled for better readability

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
