[package]
name = "osprey_math_utils"
version = "0.1.0"
edition = "2021"

[lib]
name = "osprey_math_utils"
crate-type = ["staticlib"]

[profile.release]
panic = "abort"
opt-level = 1
debug = false
overflow-checks = false
lto = false

[dependencies] 