name = "osprey-web-compiler-gateway"
compatibility_date = "2024-12-12"
main = "worker.js"

# Environment variables (set these in Cloudflare dashboard or via CLI)
# BACKEND_URL = "https://your-aws-instance.com:3001"
# ALLOWED_IPS = "1.2.3.4,5.6.7.8/24,10.0.0.0/8"
# RATE_LIMIT_PER_MINUTE = "60"

# Optional: KV namespace for rate limiting
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "your-kv-namespace-id"

# Custom domain (optional)
# routes = [
#   { pattern = "api.yourdomain.com/*", custom_domain = true }
# ]

# Logging
[observability]
enabled = true 