services:
  osprey-web-compiler:
    build:
      context: ..
      dockerfile: webcompiler/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    tmpfs:
      - /app/temp:rw,noexec,nosuid,size=256m,uid=1001,gid=1001,mode=755
    healthcheck:
      test: [
        "CMD",
        "wget",
        "--no-verbose",
        "--tries=1",
        "--spider",
        "http://localhost:3001/api",
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
